### PR TITLE
Disable ES security for Bankdemo IDE and PL/I demos

### PR DESCRIPTION
**Pull request by amy-johnstone**
- Add steps to disable ES security for tutorials. 
- Reminder at end of each tutorial to re-enable security. 
- Minor typo fixes.

### CODE REVIEW

**Comment by amy-johnstone** [comment]
@astaves @sathyav82 Could you both please review this PR and one of you merge it to 10.0 branch? Thanks.

**Review by astaves — CHANGES_REQUESTED** [review]
In 2. Should we describe how to restart MFDS and ESCWA ?  is this described in the main docs?
Also "3. Restart any running enterprise server region" should be "regions". 
There are separate versions of some of the files for Eclipse (windows), Eclipse (Unix) and VS (Windows) so not all need to have info about both Unix and Windows.

**Review by sathyav82 — COMMENTED** [review]
looks good to me - Apart from the changes already suggested by Alan

**Comment by amy-johnstone** [comment]
[Eclipse UNIX readme: Add local ESCWA] - this commit was by me, it came as a review comment from PR#21.

**Review by astaves — APPROVED** [review]
Looks ok to me now.

**Pull request merged**
