### PR TITLE
Add support for using CCITCP2_PORT env for mfds (main branch)

### PR DESCRIPTION
**Pull request by StephenGennard**
Can you consider these changes?

Background:

The current "Dockerfile" uses "sed" to amend these files, so using the env CCITCP2_PORT allows me to dup this hack.

### CODE REVIEW

**Comment by StephenGennard** [comment]
@astaves Any update?

**Review by astaves — CHANGES_REQUESTED** [review]
Sorry it's taken so long to review this but I think a few changes are needed:

1. amend_mfds_port appears to use a hardcoded MFDS UID - I think this UID can be specific to each install so needs to be obtained by using GET on http://localhost:10086/server/v1/config/mfds
2. In MF_Provision_Region you've added a catch of the exception around create_new_system but don't exit if the exception was thrown. You've also deleted a message that the pre-compiled system executables are being copied (before deploy_system_modules) which I think should remain.

**Comment by StephenGennard** [comment]
@astaves - can you review the second commit, as it has your requested changes

**Comment by StephenGennard** [comment]
@sathyav82 Any update?

**Comment by astaves** [comment]
Hi @StephenGennard The "main" branch isn't the one from which the releases are created - could you create a PR for the develop (default) branch instead ? Sorry I didn't spot this earlier.

**Comment by StephenGennard** [comment]
Thanks

**Pull request closed without merging**
